version: '3.1'

services:
  db:
    image: postgres:14.6
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslo
    volumes:
      - ./postgres:/var/lib/postgressql/data
